name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar dependencias del Backend
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          npm install

      - name: Compilar Backend
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          npm run build

      - name: Inyectar variables de entorno Backend
        run: |
          cp ~/backend.env ./backend/.env

      - name: Reiniciar Backend con PM2
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          setsid pm2 restart api-backend --update-env || setsid pm2 start dist/index.js --name "api-backend"
          pm2 save

